### PR TITLE
Issue #200

### PR DESCRIPTION
**Pull request by rinkimekari**
Added AudioMicMute, DisplayOff, and TouchpadToggle

### CODE REVIEW

**Comment by sminez** [comment]
Can you run `rustfmt` locally to fix up the lint issue please? The test failure seems to be down to compiler error messages changing yet again...I think I'm just going to have to give up on using `trybuild` 😞

**Comment by rinkimekari** [comment]
I think rustfmt was just mad about an accidental blank line. I fixed it :)

**Comment by sminez** [comment]
I've just pushed a fix for the failing `trybuild` tests on develop (updated compiler output in 1.57 broke a bunch of them which is making me really question their value over time...). Can you please rebase from the head of develop and make sure that you have a green build? I can approve after that :+1:

**Comment by rinkimekari** [comment]
All of the checks seem to have passed. Thanks for fixing it!

**Comment by sminez** [comment]
This is now published on crates.io under v0.2.1 (with your additions to the keybindings being under penrose_keysyms 0.1.1) :+1:

**Comment by rinkimekari** [comment]
Thanks!

**Comment by jasperspahl** [comment]
@sminez could you add a git tag to know on which git commit the last release is?

**Pull request merged**
