### PR TITLE
Only focus client if it was not previously focused

### LINKED ISSUE #192: Cursor is wrapped several times in the same window
### Describe the bug

Cursor is wrapped several times in some programs (e.g. steam and discord).
This is caused by `WindowManager::focus_client` not checking if the previous focused client was the same as the new focused client.

### To Reproduce

1. open steam
2. click around, see cursor constantly wrap to the center of the window.

1. open discord
2. join a voice chat
2. click `share screen`, the cursor wraps to the center of the window (this is actually a bit nice, since this is where the popup for screen selection is)

### Expected behavior

The cursor should not wrap when a window is continuously in focus. 

### Versions & OS Details

- OS: linux
- Distribution: Arch
- Penrose Version: cc36bea96eb9863a9c0ad42f42fe8c7cc2c78571

### PR DESCRIPTION
**Pull request by teo8192**
This will fix bugs with e.g. steam, where if was constantly moving the
cursor to the center of the screen, and a similar issue with discord.

Resolves #192

### CODE REVIEW

**Comment by teo8192** [comment]
Should the 'update_focus' method be called every time, or only if there is a new client in focus?

**Comment by sminez** [comment]
I've just pushed a fix for the failing `trybuild` tests on develop (updated compiler output in 1.57 broke a bunch of them which is making me really question their value over time...). Can you please rebase from the head of develop and make sure that you have a green build? I can approve after that :+1:

**Review by sminez — APPROVED** [review]
This is probably better handled by checking inside of `update_focus` if the ID being focused is the current focus. If it is we can return early there and use that to

**Comment by FredeHoey** [comment]
I ran into this yesterday, also in steam as mentioned in the original issue. Just tried with @teo8192's branch and it seems to have fixed the issue

**Comment by sminez** [comment]
This is now published on crates.io under v0.2.1 :+1:

**Comment by FredeHoey** [comment]
Awesome! Thanks for the great work

**Pull request merged**
