### PR TITLE
Fixed #138 by adding support for XF86 key bindings

### LINKED ISSUE #138: Keybindings without modifiers are marked as invalid by compile time checks
### Describe the bug

My Penrose Config wont compile if I use XF86 KeySyms

### Screenshot
```
error: proc macro panicked
   --> src/main.rs:126:24
    |
126 |       let key_bindings = gen_keybindings! {
    |  ________________________^
127 | |         // Program launchers
128 | |         "M-d" => run_external!(LAUNCHER);
129 | |         "M-Return" => run_external!(TERMINAL);
130 | |         "XF86AudioMute" => run_external!("mute");
... | |
177 | |
178 | |     };
    | |_____^
    |
    = help: message: 'XF86AudioMute' is an invalid key binding: no key name specified
            Key bindings should be of the form <modifiers>-<key name> e.g:  M-j, M-S-slash, M-C-Up
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
### Versions & OS Details

- OS: linux
- Distribution: Arch
- Penrose Version: develop at 34db716 with keysyms feature enabled

### Additional context

- [x] output of running `xmodmap -pke` (for keybinding issues)
```

keycode   8 =
keycode   9 = Caps_Lock NoSymbol Caps_Lock
keycode  10 = 1 exclam 1 exclam
keycode  11 = 2 at 2 at
keycode  12 = 3 numbersign 3 numbersign
keycode  13 = 4 dollar 4 dollar
keycode  14 = 5 percent 5 percent
keycode  15 = 6 asciicircum 6 asciicircum
keycode  16 = 7 ampersand 7 ampersand
keycode  17 = 8 asterisk 8 asterisk
keycode  18 = 9 parenleft 9 parenleft
keycode  19 = 0 parenright 0 parenright
keycode  20 = minus underscore minus underscore
keycode  21 = equal plus equal plus
keycode  22 = BackSpace BackSpace BackSpace BackSpace
keycode  23 = Tab ISO_Left_Tab Tab ISO_Left_Tab
keycode  24 = q Q q Q
keycode  25 = w W w W
keycode  26 = e E e E
keycode  27 = r R r R
keycode  28 = t T t T
keycode  29 = y Y y Y
keycode  30 = u U u U
keycode  31 = i I i I
keycode  32 = o O o O
keycode  33 = p P p P
keycode  34 = bracketleft braceleft bracketleft braceleft
keycode  35 = bracketright braceright bracketright braceright
keycode  36 = Return NoSymbol Return
keycode  37 = Control_L NoSymbol Control_L
keycode  38 = a A a A
keycode  39 = s S s S
keycode  40 = d D d D
keycode  41 = f F f F
keycode  42 = g G g G
keycode  43 = h H h H
keycode  44 = j J j J
keycode  45 = k K k K
keycode  46 = l L l L
keycode  47 = semicolon colon semicolon colon
keycode  48 = apostrophe quotedbl apostrophe quotedbl
keycode  49 = grave asciitilde grave asciitilde
keycode  50 = Shift_L NoSymbol Shift_L
keycode  51 = backslash bar backslash bar
keycode  52 = z Z z Z
keycode  53 = x X x X
keycode  54 = c C c C
keycode  55 = v V v V
keycode  56 = b B b B
keycode  57 = n N n N
keycode  58 = m M m M
keycode  59 = comma less comma less
keycode  60 = period greater period greater
keycode  61 = slash question slash question
keycode  62 = Shift_R NoSymbol Shift_R
keycode  63 = KP_Multiply KP_Multiply KP_Multiply KP_Multiply KP_Multiply KP_Multiply XF86ClearGrab
keycode  64 = Alt_L Meta_L Alt_L Meta_L
keycode  65 = space NoSymbol space
keycode  66 = Escape NoSymbol Escape
keycode  67 = F1 F1 F1 F1 F1 F1 XF86Switch_VT_1
keycode  68 = F2 F2 F2 F2 F2 F2 XF86Switch_VT_2
keycode  69 = F3 F3 F3 F3 F3 F3 XF86Switch_VT_3
keycode  70 = F4 F4 F4 F4 F4 F4 XF86Switch_VT_4
keycode  71 = F5 F5 F5 F5 F5 F5 XF86Switch_VT_5
keycode  72 = F6 F6 F6 F6 F6 F6 XF86Switch_VT_6
keycode  73 = F7 F7 F7 F7 F7 F7 XF86Switch_VT_7
keycode  74 = F8 F8 F8 F8 F8 F8 XF86Switch_VT_8
keycode  75 = F9 F9 F9 F9 F9 F9 XF86Switch_VT_9
keycode  76 = F10 F10 F10 F10 F10 F10 XF86Switch_VT_10
keycode  77 = Num_Lock NoSymbol Num_Lock
keycode  78 = Scroll_Lock NoSymbol Scroll_Lock
keycode  79 = KP_Home KP_7 KP_Home KP_7
keycode  80 = KP_Up KP_8 KP_Up KP_8
keycode  81 = KP_Prior KP_9 KP_Prior KP_9
keycode  82 = KP_Subtract KP_Subtract KP_Subtract KP_Subtract KP_Subtract KP_Subtract XF86Prev_VMode
keycode  83 = KP_Left KP_4 KP_Left KP_4
keycode  84 = KP_Begin KP_5 KP_Begin KP_5
keycode  85 = KP_Right KP_6 KP_Right KP_6
keycode  86 = KP_Add KP_Add KP_Add KP_Add KP_Add KP_Add XF86Next_VMode
keycode  87 = KP_End KP_1 KP_End KP_1
keycode  88 = KP_Down KP_2 KP_Down KP_2
keycode  89 = KP_Next KP_3 KP_Next KP_3
keycode  90 = KP_Insert KP_0 KP_Insert KP_0
keycode  91 = KP_Delete KP_Decimal KP_Delete KP_Decimal
keycode  92 = ISO_Level3_Shift NoSymbol ISO_Level3_Shift
keycode  93 =
keycode  94 = less greater less greater bar brokenbar bar
keycode  95 = F11 F11 F11 F11 F11 F11 XF86Switch_VT_11
keycode  96 = F12 F12 F12 F12 F12 F12 XF86Switch_VT_12
keycode  97 =
keycode  98 = Katakana NoSymbol Katakana
keycode  99 = Hiragana NoSymbol Hiragana
keycode 100 = Henkan_Mode NoSymbol Henkan_Mode
keycode 101 = Hiragana_Katakana NoSymbol Hiragana_Katakana
keycode 102 = Muhenkan NoSymbol Muhenkan
keycode 103 =
keycode 104 = KP_Enter NoSymbol KP_Enter
keycode 105 = Control_R NoSymbol Control_R
keycode 106 = KP_Divide KP_Divide KP_Divide KP_Divide KP_Divide KP_Divide XF86Ungrab
keycode 107 = Print Sys_Req Print Sys_Req
keycode 108 = Alt_R Meta_R Alt_R Meta_R
keycode 109 = Linefeed NoSymbol Linefeed
keycode 110 = Home NoSymbol Home
keycode 111 = Up NoSymbol Up
keycode 112 = Prior NoSymbol Prior
keycode 113 = Left NoSymbol Left
keycode 114 = Right NoSymbol Right
keycode 115 = End NoSymbol End
keycode 116 = Down NoSymbol Down
keycode 117 = Next NoSymbol Next
keycode 118 = Insert NoSymbol Insert
keycode 119 = Delete NoSymbol Delete
keycode 120 =
keycode 121 = XF86AudioMute NoSymbol XF86AudioMute
keycode 122 = XF86AudioLowerVolume NoSymbol XF86AudioLowerVolume
keycode 123 = XF86AudioRaiseVolume NoSymbol XF86AudioRaiseVolume
keycode 124 = XF86PowerOff NoSymbol XF86PowerOff
keycode 125 = KP_Equal NoSymbol KP_Equal
keycode 126 = plusminus NoSymbol plusminus
keycode 127 = Pause Break Pause Break
keycode 128 = XF86LaunchA NoSymbol XF86LaunchA
keycode 129 = KP_Decimal KP_Decimal KP_Decimal KP_Decimal
keycode 130 = Hangul NoSymbol Hangul
keycode 131 = Hangul_Hanja NoSymbol Hangul_Hanja
keycode 132 =
keycode 133 = Super_L NoSymbol Super_L
keycode 134 = Super_R NoSymbol Super_R
keycode 135 = Multi_key NoSymbol Multi_key
keycode 136 = Cancel NoSymbol Cancel
keycode 137 = Redo NoSymbol Redo
keycode 138 = SunProps NoSymbol SunProps
keycode 139 = Undo NoSymbol Undo
keycode 140 = SunFront NoSymbol SunFront
keycode 141 = XF86Copy NoSymbol XF86Copy
keycode 142 = XF86Open NoSymbol XF86Open
keycode 143 = XF86Paste NoSymbol XF86Paste
keycode 144 = Find NoSymbol Find
keycode 145 = XF86Cut NoSymbol XF86Cut
keycode 146 = Help NoSymbol Help
keycode 147 = XF86MenuKB NoSymbol XF86MenuKB
keycode 148 = XF86Calculator NoSymbol XF86Calculator
keycode 149 =
keycode 150 = XF86Sleep NoSymbol XF86Sleep
keycode 151 = XF86WakeUp NoSymbol XF86WakeUp
keycode 152 = XF86Explorer NoSymbol XF86Explorer
keycode 153 = XF86Send NoSymbol XF86Send
keycode 154 =
keycode 155 = XF86Xfer NoSymbol XF86Xfer
keycode 156 = XF86Launch1 NoSymbol XF86Launch1
keycode 157 = XF86Launch2 NoSymbol XF86Launch2
keycode 158 = XF86WWW NoSymbol XF86WWW
keycode 159 = XF86DOS NoSymbol XF86DOS
keycode 160 = XF86ScreenSaver NoSymbol XF86ScreenSaver
keycode 161 = XF86RotateWindows NoSymbol XF86RotateWindows
keycode 162 = XF86TaskPane NoSymbol XF86TaskPane
keycode 163 = XF86Mail NoSymbol XF86Mail
keycode 164 = XF86Favorites NoSymbol XF86Favorites
keycode 165 = XF86MyComputer NoSymbol XF86MyComputer
keycode 166 = XF86Back NoSymbol XF86Back
keycode 167 = XF86Forward NoSymbol XF86Forward
keycode 168 =
keycode 169 = XF86Eject NoSymbol XF86Eject
keycode 170 = XF86Eject XF86Eject XF86Eject XF86Eject
keycode 171 = XF86AudioNext NoSymbol XF86AudioNext
keycode 172 = XF86AudioPlay XF86AudioPause XF86AudioPlay XF86AudioPause
keycode 173 = XF86AudioPrev NoSymbol XF86AudioPrev
keycode 174 = XF86AudioStop XF86Eject XF86AudioStop XF86Eject
keycode 175 = XF86AudioRecord NoSymbol XF86AudioRecord
keycode 176 = XF86AudioRewind NoSymbol XF86AudioRewind
keycode 177 = XF86Phone NoSymbol XF86Phone
keycode 178 =
keycode 179 = XF86Tools NoSymbol XF86Tools
keycode 180 = XF86HomePage NoSymbol XF86HomePage
keycode 181 = XF86Reload NoSymbol XF86Reload
keycode 182 = XF86Close NoSymbol XF86Close
keycode 183 =
keycode 184 =
keycode 185 = XF86ScrollUp NoSymbol XF86ScrollUp
keycode 186 = XF86ScrollDown NoSymbol XF86ScrollDown
keycode 187 = parenleft NoSymbol parenleft
keycode 188 = parenright NoSymbol parenright
keycode 189 = XF86New NoSymbol XF86New
keycode 190 = Redo NoSymbol Redo
keycode 191 = XF86Tools NoSymbol XF86Tools
keycode 192 = XF86Launch5 NoSymbol XF86Launch5
keycode 193 = XF86Launch6 NoSymbol XF86Launch6
keycode 194 = XF86Launch7 NoSymbol XF86Launch7
keycode 195 = XF86Launch8 NoSymbol XF86Launch8
keycode 196 = XF86Launch9 NoSymbol XF86Launch9
keycode 197 =
keycode 198 = XF86AudioMicMute NoSymbol XF86AudioMicMute
keycode 199 = XF86TouchpadToggle NoSymbol XF86TouchpadToggle
keycode 200 = XF86TouchpadOn NoSymbol XF86TouchpadOn
keycode 201 = XF86TouchpadOff NoSymbol XF86TouchpadOff
keycode 202 =
keycode 203 = Mode_switch NoSymbol Mode_switch
keycode 204 = NoSymbol Alt_L NoSymbol Alt_L
keycode 205 = NoSymbol Meta_L NoSymbol Meta_L
keycode 206 = NoSymbol Super_L NoSymbol Super_L
keycode 207 = NoSymbol Hyper_L NoSymbol Hyper_L
keycode 208 = XF86AudioPlay NoSymbol XF86AudioPlay
keycode 209 = XF86AudioPause NoSymbol XF86AudioPause
keycode 210 = XF86Launch3 NoSymbol XF86Launch3
keycode 211 = XF86Launch4 NoSymbol XF86Launch4
keycode 212 = XF86LaunchB NoSymbol XF86LaunchB
keycode 213 = XF86Suspend NoSymbol XF86Suspend
keycode 214 = XF86Close NoSymbol XF86Close
keycode 215 = XF86AudioPlay NoSymbol XF86AudioPlay
keycode 216 = XF86AudioForward NoSymbol XF86AudioForward
keycode 217 =
keycode 218 = Print NoSymbol Print
keycode 219 =
keycode 220 = XF86WebCam NoSymbol XF86WebCam
keycode 221 = XF86AudioPreset NoSymbol XF86AudioPreset
keycode 222 =
keycode 223 = XF86Mail NoSymbol XF86Mail
keycode 224 = XF86Messenger NoSymbol XF86Messenger
keycode 225 = XF86Search NoSymbol XF86Search
keycode 226 = XF86Go NoSymbol XF86Go
keycode 227 = XF86Finance NoSymbol XF86Finance
keycode 228 = XF86Game NoSymbol XF86Game
keycode 229 = XF86Shop NoSymbol XF86Shop
keycode 230 =
keycode 231 = Cancel NoSymbol Cancel
keycode 232 = XF86MonBrightnessDown NoSymbol XF86MonBrightnessDown
keycode 233 = XF86MonBrightnessUp NoSymbol XF86MonBrightnessUp
keycode 234 = XF86AudioMedia NoSymbol XF86AudioMedia
keycode 235 = XF86Display NoSymbol XF86Display
keycode 236 = XF86KbdLightOnOff NoSymbol XF86KbdLightOnOff
keycode 237 = XF86KbdBrightnessDown NoSymbol XF86KbdBrightnessDown
keycode 238 = XF86KbdBrightnessUp NoSymbol XF86KbdBrightnessUp
keycode 239 = XF86Send NoSymbol XF86Send
keycode 240 = XF86Reply NoSymbol XF86Reply
keycode 241 = XF86MailForward NoSymbol XF86MailForward
keycode 242 = XF86Save NoSymbol XF86Save
keycode 243 = XF86Documents NoSymbol XF86Documents
keycode 244 = XF86Battery NoSymbol XF86Battery
keycode 245 = XF86Bluetooth NoSymbol XF86Bluetooth
keycode 246 = XF86WLAN NoSymbol XF86WLAN
keycode 247 =
keycode 248 =
keycode 249 =
keycode 250 =
keycode 251 = XF86MonBrightnessCycle NoSymbol XF86MonBrightnessCycle
keycode 252 =
keycode 253 =
keycode 254 = XF86WWAN NoSymbol XF86WWAN
keycode 255 = XF86RFKill NoSymbol XF86RFKill
```

### PR DESCRIPTION
**Pull request by jasperspahl**
Added support for XF86 key bindings

### CODE REVIEW

**Comment by sminez** [comment]
@jasperspahl can you please add some tests or at least some example output logs confirming that this works correctly for your use case and that it does not break the existing example configs?

There isn't anything there currently for the compile time validation as I haven't gotten round to it yet so I'd like to confirm everything is still fine before merging.

Also, that is an absolutely _giant_ diff... I'm not sure supporting every single XF86 key code is something Penrose needs / I am able to review. Can you trim it down to just the most common codes and then more can be added later if people need them 👍

**Review by Icelk — COMMENTED** [review]
The PR looks good!
The one thing to check are all the codes, but I doubt any are wrong.
Great work! 👍

**Comment by jasperspahl** [comment]
all codes are automatically pulled from `X11/XF86keysym.h`
using these commands  
```sh
grep "#define" /usr/include/X11/XF86keysym.h | awk '{print "/// "$2 "\n#[strum(serialize = \"" $2 "\")]\n" $2 "," }' | sed 's/= "XF86XK_/= "XF86/g' >> lib.rs

grep "#define" /usr/include/X11/XF86keysym.h | awk '{print "XF86XKeySym::"$2 " => " $3 "," }' >> lib.rs
```

sadly i haven't got any idea how to write tests in rust

**Comment by Icelk** [comment]
I’m not sure how to add tests to keybinds, but maybe link the source you pulled from for reference.
I don’t think there’s a way to check if a keybind works; you’d have to start an implementation of the WM and bind it to something showing it works.

**Comment by Icelk** [comment]
@jasperspahl If you have any idea, I’ll gladly write some rust!

**Comment by sminez** [comment]
It's more the fact that this diff is giant and unverified. I'm sorry, but it will not be being merged.

As I asked above, please cut this down to only the keybindings you need. Testing can be manual and showing the log output when you run it and bind those keys, but without that I'll need to close this PR.

**Comment by jasperspahl** [comment]
### About the size of the patch
I dont think its a good idea to add just partial support for xf86 keys
I had the idea that it could be possible to add this as a feature

### Test
i tested with this config
```rust
#[macro_use]
extern crate penrose;

use penrose::{
    core::config::Config, logging_error_handler, xcb::new_xcb_backed_window_manager, Result,
};
use simplelog::{LevelFilter, SimpleLogger};

fn main() -> Result<()> {
    if let Err(_e) = SimpleLogger::init(LevelFilter::Debug, simplelog::Config::default()) {
        panic!("unable to set log level")
    }
    let config = Config::default();
    let hooks = vec![];

    let key_bindings = gen_keybindings! {
        "M-A-Escape" => run_internal!(exit);
        "M-semicolon" => run_external!("dmenu_run");
        "M-Return" => run_external!("st");
        "M-XF86Display" => run_external!("st");

    };

    let mut wm = new_xcb_backed_window_manager(config, hooks, logging_error_handler())?;
    wm.grab_keys_and_run(key_bindings, std::collections::HashMap::new())?;

    Ok(())
}
```

everythink worked 
here is the log
```log
21:27:55 [DEBUG] (1) penrose::xcb::helpers: binding 'M-A-Escape' as [72, 66]
21:27:55 [DEBUG] (1) penrose::xcb::helpers: binding 'M-semicolon' as [64, 47]
21:27:55 [DEBUG] (1) penrose::xcb::helpers: binding 'M-Return' as [64, 36]
21:27:55 [DEBUG] (1) penrose::xcb::helpers: binding 'M-XF86Display' as [64, 235]
21:27:55 [DEBUG] (1) penrose::core::manager: Building initial workspaces
21:27:55 [DEBUG] (1) penrose::core::manager: Initialising XConn
21:27:55 [DEBUG] (1) penrose::core::manager: Attempting initial screen detection
21:27:55 [DEBUG] (1) penrose::core::manager::util: Current workspace ordering: [0, 1, 2, 3, 4, 5, 6, 7, 8]
21:27:55 [DEBUG] (1) penrose::core::manager::util: Setting focused workspace for screen Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 800, h: 600 }, effective_region: Region { x: 0, y: 18, w: 800, h: 582 } }
21:27:55 [INFO] Detected Screen: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 800, h: 600 }, effective_region: Region { x: 0, y: 18, w: 800, h: 582 } }
21:27:55 [INFO] Updating known screens: 1 screens detected
21:27:55 [DEBUG] (1) penrose::core::manager: Attempting to layout workspace 0
21:27:55 [DEBUG] (1) penrose::core::manager: Running layout_applied hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Running screens_updated hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Setting EWMH properties
21:27:55 [DEBUG] (1) penrose::core::manager: Forcing cursor to first screen
21:27:55 [DEBUG] (1) penrose::core::manager: Registering SIGCHILD signal handler
21:27:55 [DEBUG] (1) penrose::core::manager: Grabbing key and mouse bindings
21:27:55 [DEBUG] (1) penrose::core::manager: Forcing focus to first Workspace
21:27:55 [DEBUG] (1) penrose::core::manager: Running startup hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Entering main event loop
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: ScreenChange
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: SetScreenFromPoint(None)
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: RandrNotify
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: DetectScreens
21:27:55 [DEBUG] (1) penrose::core::manager: Running randr_notify hooks
21:27:55 [DEBUG] (1) penrose::core::manager::util: Current workspace ordering: [0, 1, 2, 3, 4, 5, 6, 7, 8]
21:27:55 [DEBUG] (1) penrose::core::manager::util: Setting focused workspace for screen Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 800, h: 600 }, effective_region: Region { x: 0, y: 18, w: 800, h: 582 } }
21:27:55 [INFO] Detected Screen: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 800, h: 600 }, effective_region: Region { x: 0, y: 18, w: 800, h: 582 } }
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: RandrNotify
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: DetectScreens
21:27:55 [DEBUG] (1) penrose::core::manager: Running randr_notify hooks
21:27:55 [DEBUG] (1) penrose::core::manager::util: Current workspace ordering: [0, 1, 2, 3, 4, 5, 6, 7, 8]
21:27:55 [DEBUG] (1) penrose::core::manager::util: Setting focused workspace for screen Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 800, h: 600 }, effective_region: Region { x: 0, y: 18, w: 800, h: 582 } }
21:27:55 [INFO] Detected Screen: Screen { wix: 0, true_region: Region { x: 0, y: 0, w: 800, h: 600 }, effective_region: Region { x: 0, y: 18, w: 800, h: 582 } }
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: PropertyNotify(PropertyEvent { id: 1328, atom: "_NET_SUPPORTING_WM_CHECK", is_root: true })
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: UnknownPropertyChange(1328, "_NET_SUPPORTING_WM_CHECK", true)
21:27:55 [DEBUG] (1) penrose::core::manager: GOT PROP CHANGE: id=1328 root=true atom="_NET_SUPPORTING_WM_CHECK"
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: PropertyNotify(PropertyEvent { id: 1328, atom: "WM_NAME", is_root: true })
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: ClientNameChanged(1328, true)
21:27:55 [DEBUG] (1) penrose::core::manager: Running client_name_updated hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: PropertyNotify(PropertyEvent { id: 1328, atom: "_NET_SUPPORTED", is_root: true })
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: UnknownPropertyChange(1328, "_NET_SUPPORTED", true)
21:27:55 [DEBUG] (1) penrose::core::manager: GOT PROP CHANGE: id=1328 root=true atom="_NET_SUPPORTED"
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: PropertyNotify(PropertyEvent { id: 1328, atom: "_NET_NUMBER_OF_DESKTOPS", is_root: true })
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: UnknownPropertyChange(1328, "_NET_NUMBER_OF_DESKTOPS", true)
21:27:55 [DEBUG] (1) penrose::core::manager: GOT PROP CHANGE: id=1328 root=true atom="_NET_NUMBER_OF_DESKTOPS"
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:27:55 [DEBUG] (1) penrose::core::manager: Got XEvent: PropertyNotify(PropertyEvent { id: 1328, atom: "_NET_DESKTOP_NAMES", is_root: true })
21:27:55 [DEBUG] (1) penrose::core::manager: Handling event action: UnknownPropertyChange(1328, "_NET_DESKTOP_NAMES", true)
21:27:55 [DEBUG] (1) penrose::core::manager: GOT PROP CHANGE: id=1328 root=true atom="_NET_DESKTOP_NAMES"
21:27:55 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:28:02 [DEBUG] (1) penrose::core::manager: Got XEvent: KeyPress(KeyCode { mask: 64, code: 235 })
21:28:02 [DEBUG] (1) penrose::core::manager: Handling event action: RunKeyBinding(KeyCode { mask: 64, code: 235 })
21:28:02 [DEBUG] (1) penrose::core::manager: handling key code: KeyCode { mask: 64, code: 235 }
21:28:02 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:28:02 [DEBUG] (1) penrose::core::manager: Got XEvent: MapRequest(4194310, false)
21:28:02 [DEBUG] (1) penrose::core::manager: Handling event action: MapWindow(4194310)
21:28:02 [DEBUG] (1) penrose::core::manager: Handling map request: name[st] id[4194310] class[st] type[]
21:28:02 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
21:28:35 [DEBUG] (1) penrose::core::manager: Got XEvent: KeyPress(KeyCode { mask: 72, code: 66 })
21:28:35 [DEBUG] (1) penrose::core::manager: Handling event action: RunKeyBinding(KeyCode { mask: 72, code: 66 })
21:28:35 [DEBUG] (1) penrose::core::manager: handling key code: KeyCode { mask: 72, code: 66 }
21:28:35 [DEBUG] (1) penrose::core::manager: Running event_handled hooks
```

**Comment by sminez** [comment]
Then I'm sorry but this is not being merged. The code that is erroring is the validation macro (which you can disable) and it is also possible to write your own way to generate keybindings.

Sorry, but I just can't accept a diff of this size.

**Comment by Icelk** [comment]
@sminez  Should I add support for only the most common XF86 keybinds or open an issue where people can request which should be added?

**Comment by sminez** [comment]
If you two want support for this I am definitely happy to accept a PR that is possible for me to review and that has some way of demonstrating that it does not affect existing use of Penrose.

A PR being large is not necessarily a blocker. A PRs being hundreds of lines of repetitive enum definitions with no testing or comprehensive example output _is_.
I'm sorry but I simply do not have the time to check that everything in there is good to be merged. This all came about because @jasperspahl wanted to use _a single keybinding_ without a modifier. That's fine: support for these keys is something Penrose should probably include. But I am not going to accept a diff of this size with the justification of "I ran it for one key and it was fine".

By all means raise a new PR covering adding new keys to the compile time checks (again, this feature can be disabled) but you will need to show me some proof that you have tested all of the new keys being added and that they cause no issues for the existing use of Penrose.

I use this as my daily driver and I have very little free time. Going through and verifying that everything is correct by hand is simply not something I have time to do.

**Comment by Icelk** [comment]
Right. Hope I can help and add the volume, play, pause, and skip tracks bindings.

I will post the logs of me using all keybinds.

**Pull request closed without merging**
