### PR TITLE
dmenu font

### PR DESCRIPTION
**Pull request by seanmceligot**
example:
let mut dmenu_config = DMenuConfig::default();
dmenu_config.font = String::from("NotoSans-24");
let menu = DMenu::new("filter: ", options, dmenu_config)

### CODE REVIEW

**Comment by sminez** [comment]
This is a breaking change to the public API of DMenuConfig. If you are just wanting to use a specific font when dmenu runs that's best achieved by compiling dmenu with that font specified as the default. This change looks like it would actually force "monospace" as the font for users who had changed the default font in dmenu.

**Comment by seanmceligot** [comment]
I saw monospace in PMenuConfig. I can make it `font: Option<String>` so it's not set by default. 

```
            "-l {} -nb {} -nf {} -sb {} -m {}{}",
            self.n_lines,
            self.bg_color.as_rgb_hex_string(),
            self.fg_color.as_rgb_hex_string(),
            self.selected_color.as_rgb_hex_string(),
            screen_index,
            match self.font.clone() {
                None => String::new(),
                Some(font_name) => format!(" -fn {}", String::from(font_name))
            }
```

**Comment by seanmceligot** [comment]
I see now the contrib stuff in in the FAQ. I'll open an issue later.

**Comment by sminez** [comment]
It's not about it being an Option<String> really: you are adding a public field to a struct. That is a breaking change to the codebase and I don't really want to bump the major version of the crate to add this I'm afraid.

PMenu is an internal tool where setting the default is handled in Penrose. Unlike dmenu which already has its own support for modifying the default font.

**Pull request closed without merging**
