### PR TITLE
Changed gen_keybindings! macro for more versitility

### PR DESCRIPTION
**Pull request by ghost**
Wanted to be able to format the keybinding string with not just digits but also letters, for convenience. (Also don't worry about previous pr I made, I fudged up a little, still a little new to this :p)

### CODE REVIEW

**Comment by sminez** [comment]
Hi, thanks for taking the time to raise a pr. I'm afraid I'm not going to be able to merge this however: this will panic for workspace names that are anything other than a single character that exists in the user's keymap and also only preserves the current functionality for workspaces following the default 1-9 naming.

You are able to directly bind the workspace related actions in the same way as normal key bindings which should allow you to do what you are after. If that's not sufficient, please raise an issue outlining the use case, following the issue template in GitHub.

**Comment by ghost** [comment]
Oh okay, as for the panicking is concerned though, I was able to avoid this by doing this:
```
forall_workspaces: vec!["v", "c", "x", "z"] => {
    "M-A-{}" => focus_workspace,
    "A-S-{}" => client_to_workspace,
}
```
rather than this:
```
forall_workspaces: config.workspaces => {
    "M-A-{}" => focus_workspace,
    "A-S-{}" => client_to_workspace,
}
```
from what I could tell it doesn't affect the index that will be selected from the workspaces here:
```
Some(key_code) => _map.insert(
    key_code,
    run_internal!(
        $ws_action,
        &$crate::data_types::Selector::Index(i)
    )
),
```
since it still uses the actual index of the list rather than the item.

**Comment by sminez** [comment]
That works but again is not the current behaviour so this would be a breaking change resulting in runtime panics for existing config. An extended version of the macro (or alternate macro) sounds really useful but it's no longer "forall_workspaces", rather it's "for everything in this vec".

I'd be happy to accept a PR that did not break existing config while adding this functionality by extending the macro definition rather than modifying the current behaviour. Alternatively, if you raise this as an issue I can look at implementing that macro myself as it sounds useful in more situations than just workspace related bindings 🙂

**Comment by ghost** [comment]
Well alright, I see now. I'll keep that in mind.

**Pull request closed without merging**
